### PR TITLE
[14.0][FIX] l10n_br_sale: returns a list of moves instead of record set

### LINKED ISSUE #2691: [14.0][BUG] l10n_br_sale with hr_timesheet
Após este commit https://github.com/OCA/l10n-brazil/commit/a942bff60e4fdd3407436cb2de6cacb809444b02 começamos ter erro com o módulo hr_timesheet

o refactor no l10n_br_sale retorna uma lista de moves e o hr_timesheet não consegue avançar

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1374, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/auto/addons/sale_timesheet/wizard/sale_make_invoice_advance.py", line 52, in create_invoices
    return super(SaleAdvancePaymentInv, self).create_invoices()
  File "/opt/odoo/auto/addons/sale/wizard/sale_make_invoice_advance.py", line 161, in create_invoices
    sale_orders._create_invoices(final=self.deduct_down_payments)
  File "/opt/odoo/auto/addons/sale_timesheet/models/sale_order.py", line 71, in _create_invoices
    moves._link_timesheets_to_invoice(self.env.context.get("timesheet_start_date"), self.env.context.get("timesheet_end_date"))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'list' object has no attribute '_link_timesheets_to_invoice'

cc @antoniospneto @douglascstd @aug1804 @augustodinizl @WesleyOliveira98 @kaynnan

### PR DESCRIPTION
**Pull request by marcelsavegnago**
Fix: https://github.com/OCA/l10n-brazil/issues/2691

### CODE REVIEW

**Review by renatonlima — APPROVED** [review]

**Review by antoniospneto — APPROVED** [review]
boa @marcelsavegnago ! valeu

**Review by rvalyi — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
bora mesclar :) ?

@rvalyi se puder mandar o merge eu fico feliz :heart:

**Review by augustodinizl — APPROVED** [review]

**Pull request merged**
