### PR TITLE
[12.0][FIX] Export NFref

### PR DESCRIPTION
**Pull request by gabrielcardoso21**
Export tag NFref without errors if the field document_related_id is not filled.

### CODE REVIEW

**Review by rvalyi — DISMISSED** [review]

**Comment by marcelsavegnago** [comment]
@gabrielcardoso21 deu erro no travis.. pode checar ?

**Comment by renatonlima** [comment]
@gabrielcardoso21,

Please run pre-commit

**Comment by renatonlima** [comment]
ping @gabrielcardoso21

**Comment by rvalyi** [comment]
superseded by https://github.com/OCA/l10n-brazil/pull/1532

**Pull request closed without merging**
