### PR TITLE
[FIX] inv.incoterm.freight_responsibility deve ser preenchido mesmo que ...

### PR DESCRIPTION
**Pull request by mileo**
...a transportadora não seja.

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1:

**Comment by mileo** [comment]
Already merged: https://github.com/OCA/l10n-brazil/pull/208/files

**Comment by mileo** [comment]
Already merged on 8.0

**Comment by rvalyi** [comment]
@mileo that means you approve the backport, right?

**Comment by mileo** [comment]
:+1: Yes

**Pull request merged**
