### PR TITLE
[14.0] [FIX] If you create NF-e without payment_mode_id

### PR DESCRIPTION
**Pull request by renatonlima**
Port do PR #2045

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]

**Review by rvalyi — APPROVED** [review]
LGTM

**Review by antoniospneto — APPROVED** [review]

**Review by felipemotter — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
Ta com erro no Travis

**Comment by renatonlima** [comment]
@marcelsavegnago Tudo verde

**Pull request merged**
