### PR TITLE
[MIG] l10n_br_account_product/wizard/l10n_br_account_nfe_export_invoi…

### PR DESCRIPTION
**Pull request by mileo**
…ce.py to new api

### CODE REVIEW

**Comment by renatonlima** [comment]
:+1:

**Comment by mileo** [comment]
needs fixing

**Comment by mileo** [comment]
@renatonlima fixed

**Comment by renatonlima** [comment]
@mileo 

There is a erro in nfe expor test, can you check this?

**Comment by mileo** [comment]
yes

**Comment by renatonlima** [comment]
Este PR já foi feito no #221

**Pull request closed without merging**
