### PR TITLE
[12.0][FIX] Fields and functions names (l10n_br_nfse_paulistana)

### PR DESCRIPTION
**Pull request by gabrielcardoso21**
Removes the references to a field that doesn't exist anymore in the module l10n_br_nfse_paulistana.

### CODE REVIEW

**Comment by rvalyi** [comment]
about the error you fixed in https://github.com/OCA/l10n-brazil/pull/1482/commits/35be81804231582d0eb66077d022971d8c447a3f I agree with the fix so let's apply it.

But at the same time I can find no explanation why this started to error and more importantly error inconsistently as it happened in another PR yesterday:

https://travis-ci.com/github/OCA/l10n-brazil/builds/230510535

I searched in the recent changes in Odoo 12.0 but could find no reason https://github.com/odoo/odoo/commits/12.0 so its is still a mystery for me why it started blowing out.

**Review by rvalyi — APPROVED** [review]

**Comment by mbcosta** [comment]
ola @rvalyi @gabrielcardoso21 o erro é causado por esse commit https://github.com/OCA/OCB/commit/5182be96224d2a9a82169620d276bf8399e793ad#diff-3d57dc213e6960bf9aaeaf637436ff6435776e50a55b35669baf8c0dbde7e1ec teria que confirmar se o "core" não deveria tratar a questão de receber tanto um ID quanto um Objeto/res.country

**Comment by rvalyi** [comment]
> ola @rvalyi @gabrielcardoso21 o erro é causado por esse commit [OCA/OCB@5182be9#diff-3d57dc213e6960bf9aaeaf637436ff6435776e50a55b35669baf8c0dbde7e1ec](https://github.com/OCA/OCB/commit/5182be96224d2a9a82169620d276bf8399e793ad#diff-3d57dc213e6960bf9aaeaf637436ff6435776e50a55b35669baf8c0dbde7e1ec) teria que confirmar se o "core" não deveria tratar a questão de receber tanto um ID quanto um Objeto/res.country

Eu acho que na v14 isso nao é mais problema. Porem na v12 a gente pode esquecer de alterar coisas do core, esse fix soluciona o problema de forma adequada.

**Review by mbcosta — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
