### PR TITLE
[13.0] Migration l10n_br_crm

### PR DESCRIPTION
**Pull request by luismalta**

### CODE REVIEW

**Review by renatonlima — CHANGES_REQUESTED** [review]
Please check all *.py there are some commits and changes formatting without reason

**Comment by renatonlima** [comment]
@luismalta,

I think you must rebase your branch.

**Review by renatonlima — APPROVED** [review]

**Review by mileo — APPROVED** [review]

**Comment by mileo** [comment]
@luismalta Could you upport this PR to version 14?

**Comment by mileo** [comment]
> @luismalta Could you upport this PR to version 14?

UP

**Pull request closed without merging**
