### PR TITLE
[12.0][l10n_br_hr] 12.0 pre commit l10n_br_hr

### PR DESCRIPTION
**Pull request by rvalyi**
Same reasoning as #1433 but with the module l10n_br_hr.
This PR could pass the pre-commit without special flake8 nor pylint fix.

Also in I removed the now useless @api.multi in the last commit, in the same logic as #1399

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]

**Review by renatonlima — APPROVED** [review]

**Comment by renatonlima** [comment]
@rvalyi Please rebase

**Pull request merged**
