### PR TITLE
[FIX] Onchange Fiscal Category in Purchase line.

### PR DESCRIPTION
**Pull request by mbcosta**
In some cases the same Purchase Order need to have different Fiscal Categories, but the onchange did not work.

### CODE REVIEW

**Review by vafonso — APPROVED** [review]

**Comment by rvalyi** [comment]
:+1: thanks

**Comment by renatonlima** [comment]
:+1:

**Comment by renatonlima** [comment]
Someone can review this PR?

cc @mileo @mstuttgart @danimaribeiro

**Comment by renatonlima** [comment]
Thanks @vafonso

**Pull request merged**
