### PR TITLE
[WIP] Mig/10.0

### PR DESCRIPTION
**Pull request by ghost**
Hello, this PR is for you to follow our migration, feel free to take any code, test and open issues in our repositories or even leave message in this PR.

- [x] 10n_br_base
- [x] l10n_br_data_base
- [x] l10n_br_account
- [x] l10n_br_data_account
- [x] l10n_br_account_product
- [x] l10n_br_data_account_product

This PR comes along with other two PRs. On for the [fiscal rules](https://github.com/OCA/account-fiscal-rule/pull/57) and other for the electronic documents.

### CODE REVIEW

**Comment by ghost** [comment]
@rvalyi @renatonlima @mileo @danimaribeiro 

Guys, please help us here. After [l10n_br ](https://github.com/odoo/odoo/blob/10.0/addons/l10n_br/data/account_tax_template_data.xml)migration from Odoo S.A., they removed [this tax](https://github.com/thinkopensolutions/l10n-brazil/blob/10.0/l10n_br_account_product/demo/account_tax_demo.xml#L126) ICMS 18%. Although it is used by l10n_br_account_product in some examples of demo data.

My question is if was there a specific reason for them to do that or just missed and if we should add it back in l10n_br or in l10n_br_account_product or even change the demo data.

Thanks in advance!

**Comment by danimaribeiro** [comment]
Before continuing to other modules, make sure both builds are passing. runbot and specially travis
https://travis-ci.org/OCA/l10n-brazil/jobs/178853198

Regardless your question, if you think the data is important you can put it back.

**Comment by rvalyi** [comment]
So para deixar claro, a branch 10 foi finalmente re-criada a partir dos ultimos desenvolvimentos da v8, e integrando os PR's de migracao da v9, entao esperamos os seus PR's para a branch 10 com os devidos rebases e sendo 1 PR por modulo por favor. Atts.

**Comment by rvalyi** [comment]
superseded by https://github.com/OCA/l10n-brazil/pull/516

**Pull request closed without merging**
