### PR TITLE
[16.0][l10n_br_fiscal] forward port de #3032

### PR DESCRIPTION
**Pull request by rvalyi**
forward port de #3032 (menos da parte do l10n_br_account que ainda não teve port para a v16)

### CODE REVIEW

**Review by kaynnan — APPROVED** [review]

**Review by WesleyOliveira98 — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Comment by rvalyi** [comment]
likely blocked by https://github.com/OCA/oca-addons-repo-template/issues/250 though...

**Pull request merged**
