### PR TITLE
added account_cancel dependency

### PR DESCRIPTION
**Pull request by renatonlima**
Implement the issue #166

### CODE REVIEW

**Comment by mileo** [comment]
LGTM

**Comment by renatonlima** [comment]
@mileo 

With this PR we can remove the account_cancel dependency from nfe module, https://github.com/odoo-brazil/odoo-brazil-eletronic-documents/blob/8.0/nfe/__openerp__.py#L42

cc @danimaribeiro @rvalyi

**Comment by rvalyi** [comment]
:+1:

**Comment by danimaribeiro** [comment]
:+1:

**Comment by rvalyi** [comment]
3 approvals, merging now.

**Pull request merged**
