### PR TITLE
[12.0][FIX] l10n_br_contract: fix demo data on manifest

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @gabrielcardoso21 @luismalta

**Review by jpcarassato — APPROVED** [review]
Ok

**Review by eduaparicio — APPROVED** [review]
Approved!

**Review by luismalta — APPROVED** [review]

**Review by gabrielcardoso21 — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
@OCA/local-brazil-maintainers can you merge this ?

**Review by renatonlima — APPROVED** [review]

**Pull request merged**
