### PR TITLE
[12.0][FIX] l10n_br_nfse: is not possible select city_taxation_code on product_template form

### PR DESCRIPTION
**Pull request by marcelsavegnago**
I removed this widget because I was unable to select a city tax code. Honestly, I don't know if there is a better solution but I accept suggestions.

### CODE REVIEW

**Comment by luismalta** [comment]
I really think it was a mistake of mine to use this widget. Without the widget it seems to me to be the best solution.

**Review by luismalta — APPROVED** [review]

**Comment by gabrielcardoso21** [comment]
I accessed the runbot and in the product_product form in the Invoicing app the field city_taxation_code is still not selectable. The solution would be inherit the view l10n_br_fiscal.product_form and put the field city_taxation_code after the field service_type_id. I also realized the correction you made works, but it would be best if we used this pull request to fix this other problem too.

**Comment by marcelsavegnago** [comment]
@gabrielcardoso21 Perfect. I will make the change..

**Comment by marcelsavegnago** [comment]
@gabrielcardoso21 done.. i appreciate if you review

**Review by gabrielcardoso21 — APPROVED** [review]

**Pull request merged**
