### PR TITLE
[IMP] l10n_br_base

### PR DESCRIPTION
**Pull request by max3903**
- Hide the company fields if company is not in Brazil

### CODE REVIEW

**Review by antoniospneto — APPROVED** [review]

**Review by felipemotter — APPROVED** [review]
Can you give an git amend to organize the commits?

**Review by rvalyi — APPROVED** [review]

**Review by rvalyi — CHANGES_REQUESTED** [review]
@felipemotter is right: can you squash the 2 commits?

**Comment by max3903** [comment]
@rvalyi Done!

**Review by rvalyi — APPROVED** [review]

**Pull request merged**
