### PR TITLE
trivial fix, resolve #2784

### LINKED ISSUE #2784: [14.0][15.0][16.0] git checkout on windows "" error: invalid path 'l10n_br_base/migrations/14.0.2.0.0/post-migration.py ' ""
## Module
l10n_br_base

## Describe the bug
When I git checkout on windows (for Docker environment) "" error: invalid path 'l10n_br_base/migrations/14.0.2.0.0/post-migration.py ' "" because file has got a space after ".py"
https://github.com/OCA/l10n-brazil/blob/15.0/l10n_br_base/migrations/14.0.2.0.0/post-migration.py%20

## To Reproduce
**Affected versions**: 14.0 15.0 16.0

1. On windows
2. Git clone this repo
3. git checkout 14.0

### PR DESCRIPTION
**Pull request by rpinset**
trivial fix, resolve #2784

### CODE REVIEW

**Review by rvalyi — CHANGES_REQUESTED** [review]
see my comment in #2787

**Comment by rpinset** [comment]
It's done @rvalyi 
https://github.com/OCA/l10n-brazil/pull/2788/commits/85ebb482998ff76ce0c77d7049bebe6ebf8ddc65

**Review by rvalyi — APPROVED** [review]
thank you @rpinset !

**Review by antoniospneto — APPROVED** [review]

**Comment by rvalyi** [comment]
trivial, fast tracking.

/ocabot merge patch

**Review by felipemotter — APPROVED** [review]

**Comment by rvalyi** [comment]
the merge didn't execute because the pre-commit test failed. I fixed the pre-commit in this other PR https://github.com/OCA/l10n-brazil/pull/2792
For this I had to port a few recent fixes from @mbcosta and also do 2 more commits. Rather than creating holes in the commit history, I also ported all v14 missing commits to v15 for the modules needing pre-commit fixes, that is why so many commits. No it would be cool if the reviewers here could review https://github.com/OCA/l10n-brazil/pull/2792 so we can later proceed with this merge.  cc @antoniospneto @felipemotter @marcelsavegnago @mbcosta @renatonlima

**Pull request merged**
