### PR TITLE
[12.0][IMP] l10n_br_contract: add brazilian fiscal data on contract line form

### PR DESCRIPTION
**Pull request by marcelsavegnago**
Portando da PR #2047

### CODE REVIEW

**Review by antoniospneto — APPROVED** [review]

**Review by rvalyi — CHANGES_REQUESTED** [review]
@marcelsavegnago vc viu que o Travis tava vermelho? cc @netosjb

**Review by marcos-mendez — APPROVED** [review]

**Comment by marcos-mendez** [comment]
@rvalyi eu vi isso, aqui pra mim subiu normal na lxc. Eu achei muito estranho porque não tem erro nenhum no travis ai mandei reiniciar a build, e foi. Tá errado?

**Comment by marcos-mendez** [comment]
@rvalyi porfavor se eu fiz errado da um alo ai
Screenshot from 2022-08-15 17-07-10

Eu to me aventurando agora no travis

**Comment by marcos-mendez** [comment]
@marcelsavegnago agora eu acho que entendi o erro do travis, é tipo um teste o algo assim que ele esta executando e acaba gerando um erro, mas nada tem a ver com a instalação do módulo. Só para constar.

`2022-08-15 20:21:46,780 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: ERROR

2022-08-15 20:21:46,786 8583 INFO openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: ======================================================================

2022-08-15 20:21:46,786 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: ERROR: setUpClass (odoo.addons.l10n_br_contract.tests.test_l10n_br_contract.TestL10nBrContract)

2022-08-15 20:21:46,787 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: Traceback (most recent call last):

2022-08-15 20:21:46,787 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: `   File "/home/travis/odoo-12.0/odoo/tests/common.py", line 191, in _handleClassSetUp

2022-08-15 20:21:46,787 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: `     setUpClass()

2022-08-15 20:21:46,787 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: `   File "/home/travis/build/OCA/l10n-brazil/l10n_br_contract/tests/test_l10n_br_contract.py", line 31, in setUpClass

2022-08-15 20:21:46,787 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: `     cls.contract_id.recurring_create_invoice()

2022-08-15 20:21:46,787 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: `   File "/home/travis/build/OCA/l10n-brazil/l10n_br_contract/models/contract_contract.py", line 175, in recurring_create_invoice

2022-08-15 20:21:46,787 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: `     invoices = self._recurring_create_invoice()

2022-08-15 20:21:46,787 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: `   File "/home/travis/dependencies/contract/contract/models/contract.py", line 635, in _recurring_create_invoice

2022-08-15 20:21:46,787 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: `     invoices_values = self._prepare_recurring_invoices_values(date_ref)

2022-08-15 20:21:46,787 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: `   File "/home/travis/build/OCA/l10n-brazil/l10n_br_contract/models/contract_contract.py", line 116, in _prepare_recurring_invoices_values

2022-08-15 20:21:46,787 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: `     super_inv_vals = super()._prepare_recurring_invoices_values(date_ref=date_ref)

2022-08-15 20:21:46,788 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: `   File "/home/travis/dependencies/contract/contract/models/contract.py", line 604, in _prepare_recurring_invoices_values

2022-08-15 20:21:46,788 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: `     invoice_values=invoice_values,

2022-08-15 20:21:46,788 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: ` TypeError: _prepare_invoice_line() got an unexpected keyword argument 'invoice_values'

2022-08-15 20:21:46,788 8583 INFO openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: Ran 0 tests in 2.865s

2022-08-15 20:21:46,788 8583 ERROR openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract: FAILED

2022-08-15 20:21:46,788 8583 INFO openerp_test odoo.addons.l10n_br_contract.tests.test_l10n_br_contract:  (errors=1)

2022-08-15 20:21:46,788 8583 ERROR openerp_test odoo.modules.module: Module l10n_br_contract: 0 failures, 1 errors`

**Review by felipemotter — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
@marcos-mendez Sim.. no caso o travis está retornando que um dos testes unitários não passou. Vou tentar mexer nisso ainda hoje.

**Comment by marcelsavegnago** [comment]
Agora vai.. eu tinha feito o cherry-pick de forma incorreta e acabei puxando coisa que nao deveria.

**Comment by marcelsavegnago** [comment]
@douglascstd , @marcos-mendez se puderem fazer um teste funcional eu agradeço.

**Comment by rvalyi** [comment]
> Agora vai.. eu tinha feito o cherry-pick de forma incorreta e acabei puxando coisa que nao deveria.

Droga o PR honeypot para ver quem tava de bobeira nós testes erra esse...

**Comment by marcelsavegnago** [comment]
> > Agora vai.. eu tinha feito o cherry-pick de forma incorreta e acabei puxando coisa que nao deveria.
> 
> Droga o PR honeypot para ver quem tava de bobeira nós testes erra esse...

Não tinha visto o resultado do Travis até então.. mosquei

**Comment by marcelsavegnago** [comment]
> > Agora vai.. eu tinha feito o cherry-pick de forma incorreta e acabei puxando coisa que nao deveria.
> 
> Droga o PR honeypot para ver quem tava de bobeira nós testes erra esse...

Galera nem testou :D hahahahaha

**Review by marcos-mendez — APPROVED** [review]
Agora foi tudo tracis elxc normal

**Review by rvalyi — APPROVED** [review]
LGTM

**Pull request merged**
