### PR TITLE
[FIX][REF] Fix and refactoring IE validation.

### PR DESCRIPTION
**Pull request by mbcosta**
@mstuttgart , this PR solve https://github.com/OCA/l10n-brazil/issues/412 and replace PR https://github.com/OCA/l10n-brazil/pull/413, please take a look if everything alright

### CODE REVIEW

**Comment by renatonlima** [comment]
@mbcosta please fix yml tests!

**Comment by mstuttgart** [comment]
@mbcosta it's work. Thanks!

:+1:

**Comment by renatonlima** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1: thanks

**Pull request merged**
