### PR TITLE
[12.0] l10n_br_nfe_spec

### PR DESCRIPTION
**Pull request by mileo**
Depends of https://github.com/OCA/l10n-brazil/pull/789

### CODE REVIEW

**Comment by mileo** [comment]
@renatonlima @rvalyi Travis ok now: https://travis-ci.org/odoo-brazil/l10n-brazil-wip/builds/648952324

**Comment by rvalyi** [comment]
(branch is out of date, explanations about the concept can be found here #753 )

**Comment by rvalyi** [comment]
superseded by https://github.com/OCA/l10n-brazil/pull/790 where l10n_br_nfe_spec doesn't depend on spec_driven_model anymore to make things simpler.

**Comment by marcelsavegnago** [comment]
> superseded by #790 where l10n_br_nfe_spec doesn't depend on spec_driven_model anymore to make things simpler.

It was superseded by #981 Right ?

**Comment by rvalyi** [comment]
> > superseded by #790 where l10n_br_nfe_spec doesn't depend on spec_driven_model anymore to make things simpler.
> 
> It was superseded by #981 Right ?

yes sorry.

**Comment by rvalyi** [comment]
BTW, I was focusing on bringing some polish to the most basic modules that could start getting migrated to 14, but next I get back to finishing l10n_br_nfe_spec and l10n_br_nfe.

**Comment by marcelsavegnago** [comment]
> but next I get back to finishing l10n_br_nfe_spec and l10n_br_nfe.

❤️

**Pull request closed without merging**
