### PR TITLE
Migration/l10n br product

### PR DESCRIPTION
**Pull request by renatonlima**

### CODE REVIEW

**Comment by rvalyi** [comment]
:-1: 

Sorry but this module is now empty now that the logic moved to l10n_br_account_product. The only thing it does is setting the pricelist in R$ money. We can have that in other modules. I don't think we need this module anymore just for this setting.

**Comment by rvalyi** [comment]
So I moved the pricelist setting into the the l10n_br_account module to avoid this almost empty module.

**Comment by mileo** [comment]
:1:

**Comment by mileo** [comment]
:+1:

**Pull request closed without merging**
