### PR TITLE
[FIX] Wrong function parameters

### PR DESCRIPTION
**Pull request by mileo**

### CODE REVIEW

**Comment by renatonlima** [comment]
@mileo please rebase and fix pep8

**Comment by mileo** [comment]
@renatonlima rebased and pep8 cleared

**Comment by rvalyi** [comment]
@mileo, sorry if I'm wrong about it, but I fail to see where is the bug before your patch. From the dependencies I see onchange_product_id defined here
https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L2129
and called with the proper arguments in the existing code.

Is there a special use case where this code would fail? Another module combo may be?

Now I then to agree it's more robust (change proof) to call the super onchange_product_id with keyword arguments. But if we do so, then probably it's also cleaner to have our own onchange_product_id method with keyword arguments as well here https://github.com/OCA/l10n-brazil/pull/277/files#diff-c1261c5d7b84bf43e71d5348e2cdf200L123

What do you think? Could you please give more details about the current issue? Thanks.

**Comment by danimaribeiro** [comment]
I agree that parameters seems to be right before the PR.

But :+1:  to use as the original method and merge this, it does not harm.

**Comment by rvalyi** [comment]
@mileo I vote on this if you also set keywords arguments here https://github.com/OCA/l10n-brazil/pull/277/files#diff-c1261c5d7b84bf43e71d5348e2cdf200L123
as I said in my previous comment.

**Comment by mileo** [comment]
Pelo que eu me lembro havia um erro neste trecho quando outro modulo sobrescrevia o método.

Tentei simular aqui mas faz tanto tempo que eu não me lembro, desculpe.

**Pull request closed without merging**
