### PR TITLE
[14.0][IMP] l10n_br_hr: add pis_pasep_date

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Review by augustodinizl — APPROVED** [review]
LGTM

**Review by douglascstd — APPROVED** [review]
[FUNCIONAL REVIEW] APPROVED
Inserido valor no campo de data
image
image

**Review by kaynnan — APPROVED** [review]

**Review by antoniospneto — APPROVED** [review]

**Review by aug1804 — APPROVED** [review]
It's approved for me.

**Comment by marcelsavegnago** [comment]
ping

**Review by rvalyi — APPROVED** [review]
LGTM

**Pull request merged**
