### PR TITLE
[14.0][IMP] l10n_br_sale: Hide fields if company is not in Brazil

### PR DESCRIPTION
**Pull request by max3903**
Depends on #1801

### CODE REVIEW

**Comment by rvalyi** [comment]
Thank you @max3903 the little issue I see with #1801 so var https://github.com/OCA/l10n-brazil/pull/1801/files#r893701610

**Comment by renatonlima** [comment]
@max3903,

Can you check travis status? https://app.travis-ci.com/github/OCA/l10n-brazil/jobs/573062565#L2913

**Comment by renatonlima** [comment]
@max3903,

I think you forgot define country_id field in object sale.order, You can defini country_id field in https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_fiscal/models/document_fiscal_mixin.py because this object is inherited by sale.order, purchase.order, account.move and we can reuse country_id field in other brazilian localization modules.

**Comment by rvalyi** [comment]
I also mention 2 related PR/issues that we should consider having working with this current PR:

- the idea to have a group/option to avoid having to fill the product fiscal shit, even for a Brazilian user: https://github.com/OCA/l10n-brazil/pull/1592
- getting the whole fiscal dance to work with product variants properly https://github.com/OCA/l10n-brazil/issues/1892

**Pull request closed without merging**
