### PR TITLE
[12.0][FIX] Fiscal closing error

### PR DESCRIPTION
**Pull request by gabrielcardoso21**
Fix an error while finding and creating a temp dir. It also improve the usability of fiscal closing.

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
@gabrielcardoso21 check travis error please.

**Review by mileo — APPROVED** [review]

**Comment by mileo** [comment]
@marcelsavegnago @renatonlima @rvalyi podem revisar por favor?

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by rvalyi — APPROVED** [review]

**Pull request merged**
