### PR TITLE
Fix modules version number

### LINKED ISSUE #183: Addons version numbers not compliant
I noticed the addon version numbers in this repo are not compliant with OCA rules.

You should change them from 8.0 to 8.0.1.0.0.

### PR DESCRIPTION
**Pull request by danimaribeiro**
Fix #183

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1:  perfect you also fixed the community name to the OCA

**Comment by rvalyi** [comment]
@mileo @renatonlima ok with that one guys?

**Comment by rvalyi** [comment]
in fact we should also change the versions in the README.md file. Can you complete it?
Also, I submitted this change in the README.md https://github.com/OCA/l10n-brazil/pull/187 it can be processed before or after.

**Comment by rvalyi** [comment]
OK, committing that trivial one now before we get a commit mess with the OCA bot tomorrow.

**Comment by sbidoul** [comment]
@rvalyi don't worry too much about the version numbers in README.md. This table will be maintained automatically by a bot (although currently the bot is me running the script from time to time).

**Pull request merged**
