### PR TITLE
[FIX] Field Natureza da Operação(natOp) only can have up 60 characters

### PR DESCRIPTION
**Pull request by mbcosta**
The field Fiscal Category is used at NFe as Natureza da Operação (natOp) where only can have up 60 characters.

### CODE REVIEW

**Comment by rvalyi** [comment]
@mbcosta please fix the 80 line length style issue: https://travis-ci.org/OCA/l10n-brazil/jobs/157200598#L873

**Comment by mbcosta** [comment]
Thanks @rvalyi  for review, I fixed the error and other PEP8 errors

**Comment by renatonlima** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1:

**Comment by renatonlima** [comment]
Hello guys,

This PR is open 20 days, this is very simples to review it (only one line changed without PEP8 changes), but there are only two reviews. I will schedule to merge this PR tomorrow because 20 days is enough time to review.

cc @mileo @danimaribeiro @mstuttgart

**Comment by mstuttgart** [comment]
@renatonlima I review it.

**Review by mstuttgart — APPROVED** [review]
:+1:

**Comment by renatonlima** [comment]
Thanks @mstuttgart

**Pull request merged**
