### PR TITLE
[12.0][FIX] update erpbrasil.edoc version

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Review by jpcarassato — APPROVED** [review]
Ok

**Review by eduaparicio — APPROVED** [review]
Approved!

**Comment by marcelsavegnago** [comment]
ping @gabrielcardoso21 @luismalta

**Review by renatonlima — APPROVED** [review]

**Review by rvalyi — APPROVED** [review]

**Review by gabrielcardoso21 — APPROVED** [review]

**Pull request merged**
