### PR TITLE
[FIX] Copy sale fiscal comment to invoice

### PR DESCRIPTION
**Pull request by mileo**

### CODE REVIEW

**Comment by mileo** [comment]
Depende do https://github.com/OCA/l10n-brazil/pull/435 para aumentar o coverage.

@lfdivino inclusive se vc conseguir no teste as observações do pedido seria bacana.

**Comment by renatonlima** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1:

**Comment by sadamo** [comment]
:+1:

**Pull request merged**
