### PR TITLE
Fixing typo that generates an error in Fiscal Position template

### PR DESCRIPTION
**Pull request by danimaribeiro**
Fix small error, change 'purhcase' for 'purchase'

### CODE REVIEW

**Comment by yvaucher** [comment]
What is the `develop` branch in here?

Was this fixed?

**Comment by danimaribeiro** [comment]
The develop branch is a second version of localization for version 7.0 with more improvements and a few refactories.

This was not fixed yet, it needs to be merged and reviewed.

**Comment by yvaucher** [comment]
@danimaribeiro Ok thanks this change is fine :+1:

**Comment by rvalyi** [comment]
:+1:  good catch.

**Pull request merged**
