### PR TITLE
Migration/l10n br data account product

### PR DESCRIPTION
**Pull request by renatonlima**

### CODE REVIEW

**Comment by renatonlima** [comment]
I will squash these commits 0fddf4a ef1d6d4

**Comment by rvalyi** [comment]
please remove empty data files

**Comment by rvalyi** [comment]
:+1:

**Comment by mbcosta** [comment]
:+1:

**Comment by rvalyi** [comment]
only need to change the module author name to Odoo Community Association

**Comment by rvalyi** [comment]
:+1:

**Pull request merged**
