### PR TITLE
Migration/l10n br crm zip

### PR DESCRIPTION
**Pull request by renatonlima**

### CODE REVIEW

**Comment by danimaribeiro** [comment]
Zip search not working:

```
File "/home/danimar/projetos/odoo_demo/OCB/addons/web/controllers/main.py", line 936, in _call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
File "/home/danimar/projetos/odoo_demo/OCB/openerp/api.py", line 241, in wrapper
return old_api(self, *args, **kwargs)
File "/home/danimar/projetos/odoo_demo/oca-l10n-brazil/l10n_br_crm_zip/models/crm_lead.py", line 43, in zip_search
zip_data, self._name, ids[0])
 File "/home/danimar/projetos/odoo_demo/OCB/openerp/api.py", line 241, in wrapper
return old_api(self, *args, **kwargs)
File "/home/danimar/projetos/odoo_demo/OCB/openerp/api.py", line 335, in old_api
recs = self.browse(cr, uid, [], context)
File "/home/danimar/projetos/odoo_demo/OCB/openerp/api.py", line 241, in wrapper
return old_api(self, *args, **kwargs)
File "/home/danimar/projetos/odoo_demo/OCB/openerp/models.py", line 5224, in browse
return self._browse(Environment(cr, uid, context or {}), ids)
File "/home/danimar/projetos/odoo_demo/OCB/openerp/api.py", line 713, in __new__
self.cr, self.uid, self.context = self.args = (cr, uid, frozendict(context))
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by danimaribeiro** [comment]
@renatonlima You can merge this one, then I send the migration to new api. It's the same code from zip.

**Comment by renatonlima** [comment]
This PR is finishing by @danimaribeiro in #165

**Comment by danimaribeiro** [comment]
Could you reopen this and merge it? I could not rebase it to implement the changes.

**Pull request closed without merging**
