### PR TITLE
[IMP] Mock zip tests

### PR DESCRIPTION
**Pull request by mileo**
Some times travis fail because some issue with the Correios Webservice.

### CODE REVIEW

**Comment by rvalyi** [comment]
I'm not so sure if it's a good idea in the case of the correios. All in all it hardly fails once every 100 Travis run or more. The mock would bring this down to zero, but it will also fail silently if there is a webserice change as it happened a few months ago. So all in all I'm not in favor of the change here. (it's not the same with the NFe, for once because not mocking would slow down a lot more and also because everybody is watching after any possible NFe webservice change so they wouldn't be missed more than a day anyway).

**Comment by mileo** [comment]
Ocorreu no merge desse PR:

Link correto: https://github.com/OCA/l10n-brazil/pull/1270

https://travis-ci.com/github/OCA/l10n-brazil/jobs/499482447#L3969

**Review by rvalyi — APPROVED** [review]
Bom realmente tou vendo mais problemas com os site dos correios ultimamente, entao bora fazer o merge desse. Porem talvez precisa desse primeiro https://github.com/OCA/l10n-brazil/pull/1304
Vamos ver se esse vai se nao a gente faz um PR combinado. Tb teve falha com l10n_br_website_sale no ultimo run entao estamos cercados...

**Review by renatonlima — APPROVED** [review]

**Pull request merged**
