### PR TITLE
Odoo Brazil github static page for www.odoobrasil.org.br

### PR DESCRIPTION
**Pull request by mileo**
Hi,

The proposal of this PR is to activate a github static page for Odoo Brazil (www.odoobrasil.org.br) with this resources:
- [X] Website;
- [ ] Blog;
- [ ] Functional Documentation, generated with sphinix robotframework;
- [X] Technical Documentation, generated with sphinix-autodoc;
- [ ] Automatic build and deploy this features with travis and update github static page;

### CODE REVIEW

**Comment by mileo** [comment]
An example of a similar implementation we can see here:

http://odoo-magento-connector.com/ 
https://github.com/OCA/connector-magento

@OCA/board Can some one please:
- [ ] Configure the github page domain: odoobrasil.org.br ( Registred last week by me and @renatonlima  in name of "Associação Python Brasil"  009.344.485/0001-05 for we can have a org domain in Brazil)

Thanks

**Comment by mileo** [comment]
Here is the example of Functional documentation and tests with robotframework https://github.com/kmee/odoo-travis-robotframework

It's a WIP project but you can see:
- Documentation output https://github.com/kmee/odoo-travis-robotframework/blob/master/docs/source/sale/index.rst.txt
- Travis tests with chorome and selenium https://travis-ci.org/kmee/odoo-travis-robotframework#L2668

**Comment by renatonlima** [comment]
Hello @rvalyi,

I think you can do it:
- Configure the github page domain: odoobrasil.org.br ( Registred last week by me and @renatonlima in name of "Associação Python Brasil" 009.344.485/0001-05 for we can have a org domain in Brazil)

**Comment by rvalyi** [comment]
@renatonlima nope, OCA projects settings changed a while back and I don't have the project settings access anymore myself. But will check that with Seb.

**Comment by mileo** [comment]
@max3903 @pedrobaeza Can you help us?

- Configure the github page domain: odoobrasil.org.br ( Registred last week by me and @renatonlima in name of "Associação Python Brasil" 009.344.485/0001-05 for we can have a org domain in Brazil)

**Pull request closed without merging**
