### PR TITLE
[12.0][FIX] Edoc Cancelada Workflow

### PR DESCRIPTION
**Pull request by luismalta**
Cancel document with document workflow

### CODE REVIEW

**Review by mileo — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by rvalyi — DISMISSED** [review]
o Travis ta vermelho https://travis-ci.org/github/OCA/l10n-brazil/builds/735835552

**Comment by mileo** [comment]
@luismalta https://travis-ci.org/github/OCA/l10n-brazil/jobs/735835553#L434 faltou remover as constantes do arquivo.

**Pull request merged**
