### PR TITLE
[MIG] Change the version of module.

### PR DESCRIPTION
**Pull request by mbcosta**

### CODE REVIEW

**Comment by danimaribeiro** [comment]
:+1: 
Just the building is failling, but because the travis points to branch 9.0 of Pysped which does not exist. Can you change to 8.0 in this PR to make it pass

**Comment by danimaribeiro** [comment]
I made a patch:
https://github.com/OCA/l10n-brazil/pull/300
Let's see if it fix the build, then we can start from there.

**Comment by renatonlima** [comment]
:+1:

**Comment by mileo** [comment]
:+1:

**Pull request merged**
