### PR TITLE
10.0 mig l10n br sale

### PR DESCRIPTION
**Pull request by mileo**
Depende de #603

### CODE REVIEW

**Review by rvalyi — CHANGES_REQUESTED** [review]
same comment:
thanks!! however you need to trim the ```<data></data>``` tags as they are not required anymore. Eventually as there is no XML change, you can also make a separate commit to ensure XML indentation is conform to OCA standards if it is not (the sooner we tackle these things, the earlier we make cherry picking between next branches easy).

**Comment by rvalyi** [comment]
can you rebase on 10.0 and fix the conflicts please?

**Review by rvalyi — DISMISSED** [review]
Thanks for the work. However, the module has not been set as uninstallable in the manifest file. That is why the coverage didn't decrease. We would need tests too... Typically the test from l10n_br_sale_stock could be adapted. But that would be good to have the test in Python rather than yaml then... cc @renatonlima @mbcosta

**Comment by the-bmb** [comment]
Depende do PR https://github.com/OCA/account-fiscal-rule/pull/86

**Comment by mileo** [comment]
Substituído por https://github.com/OCA/l10n-brazil/pull/648

**Pull request closed without merging**
