### PR TITLE
PEP8 on base and CRM module

### PR DESCRIPTION
**Pull request by mbcosta**
Replace depreciated api.one decorator and remove excess space on license header.

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1:

**Comment by renatonlima** [comment]
:+1:

**Comment by rvalyi** [comment]
@api.constrains needs an @api.multi indeed. But then their logic should then be wrapped in loops instead of having that incompatible ensure_one.

**Comment by mbcosta** [comment]
Thanks @rvalyi for review, I change all constrains in base and crm

**Pull request merged**
