### PR TITLE
[MIG] Migration of l10n_br_crm_zip to new api.

### PR DESCRIPTION
**Pull request by mstuttgart**
- ZIP Search Integration for Brazilian Localization of CRM module.
- Migrated to apiv v8

### CODE REVIEW

**Comment by danimaribeiro** [comment]
:+1: 
Just fix those flake8 problems and it's ok.
https://travis-ci.org/OCA/l10n-brazil/jobs/79153489

**Comment by mstuttgart** [comment]
Flake8 problems fixed.

**Comment by danimaribeiro** [comment]
:+1:

**Comment by renatonlima** [comment]
:+1:

**Pull request merged**
