### PR TITLE
Feature/l10n br commission

### PR DESCRIPTION
**Pull request by mileo**

### CODE REVIEW

**Comment by danimaribeiro** [comment]
Esse módulo depende de algum módulo especial além do https://github.com/OCA/commission
pois eu não consegui localizar o método condition_state_invoice no sale_commission.

**Comment by mileo** [comment]
Danimar, 

Esse pr da comissão precisa de uma modificação que fizemos no modulo da OCA. 

Essa modificação foi feita com uma branch antiga, vou corrigir o problema o mais breve e enviar o pull request lá também. 

Abraços 

## 

Luis Felipe Miléo 
KMEE 
+55 35 8876-3663 
+55 35 3622-2548 
skype: luisfelipemileo 
mileo@kmee.com.br 
kmee.com.br 

De: "Danimar Ribeiro" notifications@github.com 
Para: "OCA/l10n-brazil" l10n-brazil@noreply.github.com 
Cc: "Luis Felipe Miléo" mileo@kmee.com.br 
Enviadas: Quarta-feira, 11 de fevereiro de 2015 14:18:42 
Assunto: Re: [l10n-brazil] Feature/l10n br commission (#123) 

Esse módulo depende de algum módulo especial além do https://github.com/OCA/commission 
pois eu não consegui localizar o método condition_state_invoice no sale_commission.

**Comment by rvalyi** [comment]
Ola, se vc faz esse modulo depender da nova versao do modulo de commissao da OCA re-trabalhada pelo Pedro Baeza, poderiamos incluir esse modulo nesse repo aqui sim eu acho. Valeu. @renatonlima o que acha?

**Comment by rvalyi** [comment]
@mileo I propose to close that one untill you eventually propose a clean version based on latest 8.0 branch. Meanwhile feel free to use the odoo-brazil repo https://github.com/odoo-brazil/odoo-brazil-commission to host some eventual prototype.

**Comment by danimaribeiro** [comment]
What about leave it open to no forget about it?

**Comment by rvalyi** [comment]
@danimaribeiro looks like it's really not being worked on. What I have seen is a prototype based on the old API and before lot's of refactored happen. All in all it's very probable it will need to mature 1st n odoo-brazil which will be more agile. And after it becomes somwhat in shape, this is yet to be decided if we accept it in this repo (I'm open to it, that's a small and clean dep). Also nobody is going to forget commissions in Brazil this is just beeing asked too often. BTW we made the same kind of pre-API change as KMEE and put it at only one customer and had no time for taking care to upstream that work unfortunately. In the meantime there are many PR already and v9 is gong to bring us the double so I prefer trashing what is very unlikely to happen in v8 anymore.

**Comment by rvalyi** [comment]
but if some credible new API v8 commission PR is made by somebody, we will surely re-open it.

**Comment by rvalyi** [comment]
@danimaribeiro BTW it has been voted by the OCA maintainer that we are encouraged to close the unactive PR's after 6 months: https://github.com/OCA/maintainer-tools/pull/120
I will not apply that blindly here because I know we screwed the v8 migration schedule for an exceptional reason, but as you see, I even voted for a 1 year time frame...

**Pull request closed without merging**
