### PR TITLE
[FIX] Error on create purchase_order

### PR DESCRIPTION
**Pull request by mstuttgart**
UnboundLocalError: local variable 'kwargs' referenced before assignment

### CODE REVIEW

**Comment by renatonlima** [comment]
@mstuttgart 

There is a problem in PySPED dependency, Perhaps a temporary problem during the build, can you check it?

cc @rvalyi @mileo @danimaribeiro

**Comment by mileo** [comment]
Hi i try this fix https://github.com/odoo-brazil/pyxmlsec/commit/0646aa962cc9eadcc4ba4cbb267a6afb69977cb6

**Comment by renatonlima** [comment]
@mileo 

In this case simply make a rebase to rebuild travis, right?

**Comment by renatonlima** [comment]
:+1:

**Comment by mbcosta** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1: thanks

**Pull request merged**
