### PR TITLE
[14.0][l10n_br_fiscal] Melhorias nas visões do documento Fiscal

### PR DESCRIPTION
**Pull request by renatonlima**
Removido algumas mensagens de logs

Screenshot from 2023-07-07 13-27-30

Adicionado alguns filtros do status e datas

Screenshot from 2023-07-07 16-47-48

### CODE REVIEW

**Review by antoniospneto — APPROVED** [review]

**Review by vanderleiromera — APPROVED** [review]

**Review by rvalyi — DISMISSED** [review]
LGTM

**Review by rvalyi — CHANGES_REQUESTED** [review]
OK with the idea but the view format is not correct and the pre-commit failed.

**Review by marcelsavegnago — APPROVED** [review]

**Review by rvalyi — APPROVED** [review]

**Pull request merged**
