### PR TITLE
Migration/l10n br stock

### PR DESCRIPTION
**Pull request by renatonlima**

### CODE REVIEW

**Comment by renatonlima** [comment]
@rvalyi @mileo @danimaribeiro 

I take a look in https://github.com/odoo-brazil/l10n-brazil and see the module l10n_br_stock is not split in l10n_br_stock and l10n_br_stock_account, I did this in https://github.com/akretion/l10n-brazil/tree/migration/l10n_br_stock, please check this migration feature branch and tell me what we can integrate in this branch

**Comment by mileo** [comment]
:+1:

Split é necessário.

**Comment by rvalyi** [comment]
l10n_br_stock_account included in this PR won't install on Travis until we get this merge:
https://github.com/OCA/account-fiscal-rule/pull/30

**Comment by rvalyi** [comment]
OCA/account-fiscal-rule#30 is merged so it's entirely on our side now...

**Comment by rvalyi** [comment]
very strange that we got a failure in l10n_br_account in the OCB repo here...

**Comment by rvalyi** [comment]
cc @danimaribeiro @mileo review welcome.
please see the extensive testing https://github.com/akretion/l10n-brazil/tree/migration/l10n_br_stock/l10n_br_stock_account/test

**Comment by mileo** [comment]
:+1: But if you can squash some commits

**Comment by rvalyi** [comment]
:+1:
I think we can squash some 5-6 commits before merging indeed.

**Comment by rvalyi** [comment]
branch backed up here https://github.com/akretion/l10n-brazil/commits/migration/l10n_br_stock-bk
from which I squashed 6a68e95 915952a 9b32ec6 aa1c534
merging now...

**Pull request merged**
