### PR TITLE
FIX: AccessError (Modelo de documento: sale.advance.payment.inv)

### PR DESCRIPTION
**Pull request by rvalyi**
@mileo here you go.

cc @yk2kus @cmsalmeida @danimaribeiro @renatonlima @mstuttgart

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1:

**Comment by mileo** [comment]
:+1:

**Comment by rvalyi** [comment]
@mileo  ?

**Comment by mileo** [comment]
Refresh please, I messed up typing

**Comment by mileo** [comment]
3g connection, no symbols displayed....

**Comment by renatonlima** [comment]
:+1:

**Pull request merged**
