### PR TITLE
[14.0][FIX] l10n_br_nfse_focus: fix make pdf and transmission

### PR DESCRIPTION
**Pull request by marcelsavegnago**
This pull request introduces several enhancements and bug fixes to the `l10n_br_nfse_focus` module, focusing on improving the handling of document status updates, cancellations, and PDF content verification. The most critical changes include modifications to the `_prepare_payload`, `_document_status`, and `cancel_document_focus` methods, as well as the addition of new fields in the `ResCompany` model.

### Enhancements to document processing:

* [`l10n_br_nfse_focus/models/document.py`](diffhunk://#diff-787684de500e7c4c1f6be4e0433995f07463299b45bfbfc7ebea1072c2807775L148-R159): Refactored the `_prepare_payload` method to conditionally include `codigo_obra` and `art` fields only when they are present.
* [`l10n_br_nfse_focus/models/document.py`](diffhunk://#diff-787684de500e7c4c1f6be4e0433995f07463299b45bfbfc7ebea1072c2807775L364-R388): Improved the `_document_status` method to handle additional document states and introduced a new method `fetch_and_verify_pdf_content` for better PDF content validation. [[1]](diffhunk://#diff-787684de500e7c4c1f6be4e0433995f07463299b45bfbfc7ebea1072c2807775L364-R388) [[2]](diffhunk://#diff-787684de500e7c4c1f6be4e0433995f07463299b45bfbfc7ebea1072c2807775L427-R516)

### Enhancements to document cancellation:

* [`l10n_br_nfse_focus/models/document.py`](diffhunk://#diff-787684de500e7c4c1f6be4e0433995f07463299b45bfbfc7ebea1072c2807775L447-R550): Enhanced the `cancel_document_focus` method to create a cancel event if the document is already canceled and introduced a new method `create_cancel_event` to handle event creation. [[1]](diffhunk://#diff-787684de500e7c4c1f6be4e0433995f07463299b45bfbfc7ebea1072c2807775L447-R550) [[2]](diffhunk://#diff-787684de500e7c4c1f6be4e0433995f07463299b45bfbfc7ebea1072c2807775L483-R597)

### New fields in `ResCompany` model:

* [`l10n_br_nfse_focus/models/res_company.py`](diffhunk://#diff-f12beb3627b0305b4cc8fba680c06ae6a6343e027740b803bd5ddc690d34cf8fR43-R58): Added `focusnfe_nfse_update_authorized_document_status` and `focusnfe_nfse_force_odoo_danfse` fields to control document status updates and PDF generation behavior.
* [`l10n_br_nfse_focus/views/res_company.xml`](diffhunk://#diff-9ed7e7c45752c897d9c5378f48af5675170705aa4e1e74710339d64ba32f522fR30-R37): Updated the view to include the new fields `focusnfe_nfse_update_authorized_document_status` and `focusnfe_nfse_force_odoo_danfse`.

### CODE REVIEW

**Comment by mileo** [comment]
essa trecho de código do pdf da pra encapsular né?

**Comment by marcelsavegnago** [comment]
@mileo vou melhorar isso.. deixar mais limpo

**Review by rvalyi — APPROVED** [review]
LGTM (code, no test on my side)

**Review by antoniospneto — APPROVED** [review]
por mim ok

**Review by mileo — APPROVED** [review]

**Pull request merged**
