### PR TITLE
prototipo nova versão da localização brasileira v10

### PR DESCRIPTION
**Pull request by mileo**
Comportamento esperado depois do PR:
------------------------------------
- [X] Módulo financeiro; https://github.com/OCA/l10n-brazil/pull/520
- [X] Módulo fiscal reestruturado; https://github.com/OCA/l10n-brazil/pull/518
- [X] Módulo de transmissão de nfe e nfce;

Roadmap:
https://docs.google.com/document/d/1JNJgapClBnDvpT-GphJyLrhLP5azn_D8g9TXjbESdB4/edit?pli=1#heading=h.jfitt9pmfp7d

Substitui o PR:
https://github.com/OCA/l10n-brazil/pull/527

Runbot para testes:
http://runbot.kmee.com.br/runbot/repo/git-github-com-odoo-brazil-l10n-brazil-wip-git-3

### CODE REVIEW

**Comment by rvalyi** [comment]
Guys, there is lot of work currently done in https://github.com/odoo-brazil/l10n-brazil-wip

A big issue however is that this work is done completely out of the OCA process, bypassing the review, the tests and the nature of the PR's.

We understand that a shortcoming of the OCA is its rigidity and this is exactly the reason why we advocated long ago for splitting the more experimental features in non OCA projects and avoiding to bloat the OCA localization and paralyzing it. We also totally supported prototypying some refactors in such a "wip" branch to speed up experimentation.

I and @renatonlima (both PSC's of the project) think it now becomes urgent to consolidate the work of  https://github.com/odoo-brazil/l10n-brazil-wip inside the OCA.

That is why we suggest people contributing to https://github.com/odoo-brazil/l10n-brazil-wip to take a step back, use git filter-branch and start making PR's against the OCA repo, module by module as usual for human review, starting from the root: l10n_br_base (at the moment no such PR existed). Aditional features such as financial module are welcome, but they are less prioritary and when they depend on upstream modules beging refactored, these upstream module should land in the OCA first otherwise it is just plain impossible to review.

Of course as for the other migrations, a consolidated branch such as https://github.com/odoo-brazil/l10n-brazil-wip might still make sense for people ready to assume experimental features. But our fear is that if we wait too long before the OCA consolidation, we may have users using https://github.com/odoo-brazil/l10n-brazil-wip without being actually ready to refactor and migrate heavily once switching to the OCA and we would be again back to the pre-OCA situation where every company do stuff on their side without proper integration. Other risks include loosing the test coverage of the current project, or making the migration very difficult for the dozens of companies using the OCA localization etc...


Off topic: as announced, I'm personally working on expanding the boleto/CNAB features significantly interfacing the mature and well maintained https://github.com/kivanio/brcobranca with the project. Will soon publish a prototype (by its nature will probably be a non OCA module however though).

Regards.

cc @mileo @aricaldeira @renatonlima @mbcosta

**Comment by mileo** [comment]
@rvalyi Can you make the filter branch?

**Comment by rvalyi** [comment]
@mileo. Yes I think I can do it later in the day. Also basically I believe @renatonlima made fez remarks about refactors (he explained me) and I think aren't yet been taken into account in the wip branch. They can be done before or after the filter-branch but I believe they are important too.

**Comment by rvalyi** [comment]
the git filter-branch action isn't trivial, but I think I finally nailed it. Stay tuned for the PR...

**Comment by rvalyi** [comment]
and here goes the first round for l10n_br_base https://github.com/OCA/l10n-brazil/pull/536
cc @renatonlima @mileo @aricaldeira

**Comment by rvalyi** [comment]
so the script is roughly:

given you have a local clone with both the OCA 10.0 branch and teh odoo-brazil 10.0-develop branch, we should first find out the last common ancestor of the 2 branches and this is done with:
`merge_base=$(git merge-base 10.0-develop 10.0)`

Then we will need a copy of the codebase of the OCA 10.0 branch at this specific commit, so checkout this commit and but it in some directory here named 'v10_dir'.

the run the following script to produce an extracted branch:

```
module="l10n_br_base"

git checkout 10.0-develop
git branch -D "10.0-wip-$module"
git branch "10.0-wip-$module"
git checkout "10.0-wip-$module"
git filter-branch -f --subdirectory-filter "$module" -- "$merge_base..HEAD"
git filter-branch -f --tree-filter "mkdir -v $module; git mv -k * $module; rsync -av $v10_dir/* . --exclude $module; cp -r $v10_dir/.github .; cp $v10_dir/.codeclimate.yml .; cp $v10_dir/.coveragerc .; cp $v10_dir/.gitignore .; cp $v10_dir/.travis.yml .; git add *;" "$merge_base..HEAD"
```

**Comment by rvalyi** [comment]
NOTE: once an extracted PR will be merged into the OCA v10 branch, in the odoo_brazil wip branch, you will safely be able to do a commit that will switch the wip module by the new OCA v10 module (as it will probably get some change to get accepted in the OCA). This won't create mess as when merging the next modules, the git-filter branch will simply skip the commits related to this previous module.

**Comment by pedrobaeza** [comment]
You can use also these instructions changing the source branch and remote:

**Comment by pedrobaeza** [comment]
Sorry, my fault pressing the button from the mobile incorrectly.  Here it's the link: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by rvalyi** [comment]
thanks @pedrobaeza in our case this is much more complex though and there are 2 reasons mostly:

  1) instead of first porting all the module to v10 they tried to ALSO include new features altogether with the migration... The reason is mostly that a guy made quite good stuff but as closed source since 2011. We could convince him to contribute to the OCA, but instead of adapting his code to the OCA, he kind of replaced the OCA code by its own codebase trying to take some of our remarks into account to achieve some of the modularity we have in the OCA. So now we are still left with a big refactor to adapt his experimental code to the one of the OCA instead wherever possible to make migration smoother and not throw away dozens of years man of experience and real life deployments in the existing codebase. We are open to refactors when they make senses but that should be part of the standard OCA review with the PSC's as separated PR's after the migration work otherwise it's impossible to review what is lost vs what is won (like currently that Work In Progress branch is kind of simply dropping the 70% of test coverage we had in the project...).

 2) Moreover, the branch they used for that prototyping is not a fork (or a rebase) of the current OCA 10 version, but instead some kind of previous branch where some OCA code has been merged, this is the reason why simple rebase won't work and why I had to restore the codebase in the filter-branch to keep a bit of their refactor history of what they did when trying to make their codebase more modular and include new features instead first focusing on the OCA merges.

But yeah, still some hard work ahead...

**Comment by pedrobaeza** [comment]
Well, good luck then with the work... sorry for not being helpful

**Comment by rvalyi** [comment]
@pedrobaeza you are always extremely useful in your daily OCA work and we would never thank you enough for that. But in any case we are kind of merging two huge code bases now and adapt to the v10 accounting refactor so it is a bit normal it is a huge task. We will make it still!

**Comment by pedrobaeza** [comment]
You have enough skills for sure!!

**Comment by rvalyi** [comment]
so for the record, I let a comment here too: currently the WIP branch got wrong with the orientation from the project leader @renatonlima who defined a way to properly refactor the new sped module for merge-ability into the OCA branch. There has been a wrong commit that screwed that merge-ability. I'm fixing this with git filter-branch now... More details here in the PR for the l10n_br_base extraction:
https://github.com/OCA/l10n-brazil/pull/542#issuecomment-307399186

**Comment by rvalyi** [comment]
so as I promised I fixed the bad git operation that screwed the OCA merge-ability by removing the OCA files form the history. @mileo, after checking I will need you to switch the wip branch by this new wip mergeable branch https://github.com/odoo-brazil/l10n-brazil-wip/tree/10.0-develop-mergeable-oca

As it is using git filter-branch that may  difficult the next merges against the WIP branch so eventually process your main merges BEFORE doing the switch.

One can redo the new mergeable WIP branch at anytime with the following script:

```
merge_base=9685798bc47b6168d80a5d8042070b75c60faa48
last_mergeable_dir=/home/rvalyi/DEV/OCA/l10n-brazil/wip-10-last-mergeable

git checkout 10.0-develop

git branch -D "10.0-wip-mergeable"
git branch "10.0-wip-mergeable"
git checkout "10.0-wip-mergeable"


git filter-branch -f --tree-filter "cp -rn $last_mergeable_dir/l10n_br_base/* l10n_br_base/; git add *;" "$merge_base..HEAD"
```

cc @renatonlima @aricaldeira @mbcosta 
Note that I'm not against suggestion of doing further changes in that rewrite script as long as it doesn't loose the OCA files history and ability to merges their changes back into the OCA.

Me an @mbcosta are currently working on refactoring the WIP branch / sped module to get it use the OCA base module as much as possible ate least before eventually applying larger conceptual changes but in an OCA controlled way and preserving tests of the OCA modules, not in freestyle.

**Comment by rvalyi** [comment]
guys, aside from correcting the git history, I also split the first modules that we could think merging into the OCA (the process is easily repeatable as new commits are added, It doesn't use the wip branch with the fixed git history at the time I'm writing this). We can use these PR's to track the OCA feedback and acceptance:

- [ ] copy_views: https://github.com/OCA/l10n-brazil/pull/544 Should ideally go into https://github.com/OCA/server-tools but it's okay to have it here in case it takes too much time to get it merged into server_tools

- [ ] l10n_br_base: https://github.com/OCA/l10n-brazil/pull/542 However, this comparison by @mbcosta https://docs.google.com/spreadsheets/d/1EVTWXOW6c6gkJ_JyLTZSj4BJRr5u_MdehuwZ4EhX9D4 shows us we are still very far from being able to properly reuse the OCA module in the sped module. Morever the complete lack of test in the sped_* modules make refactoring these modules really risky at the moment... Not to say the generalization of the _inherits design is something that I am personally against (because it will fuck with all extension points in Odoo core modules and OCA modules) and is something that will totally conflict with the current OCA modules. All in all, I suggest extracting a sub module such as some l10n_br_base_lib where we could progressively factor what is common between the sped module and the OCA modules until eventually the sped module is able to use the l10n_br_base module some day...

- [ ] sped: https://github.com/OCA/l10n-brazil/pull/548 (see previous remark)

- [ ] sped_imposto: https://github.com/OCA/l10n-brazil/pull/547 could we have it depend on such a new l10n_br_base_lib lib so it won't conflict with the OCA l10n_br_base module? Eventually there is some hope here...

**Comment by mbcosta** [comment]
Hi all,
 I made a superficial review and I found some points until now:
      - The most python files ( *.py ) don't have the blank line at the end of file ( PEP8 ), what make PyLint return error on tests
      - Attribute _name and _inherit in the same class , I not sure about this, but I think it can cause errors 
      - The object sped.soma.imposto( sped_imposto/models/sped_soma_imposto.py ) seems not be used, it's right ?
```
grep -rn 'sped.soma.imposto' --include \*.py ../l10n-brazil-wip/
../l10n-brazil-wip/sped_imposto/models/sped_soma_imposto.py:28:    _name = b'sped.soma.imposto'
../l10n-brazil-wip/sped_imposto/models/__init__.py:41:from . import sped_soma_imposto
```

**Pull request closed without merging**
