### PR TITLE
[12.0] [IMP] danfse layout

### PR DESCRIPTION
**Pull request by ygcarvalh**
Hello guys. I'm opening this PR with improvements to the danfse print layout. The following changes have been made:

- Change in the style of the classes, such as margin and padding;
- Lovigo size of the service proder company;
- The outlines of the table cells.

Two situations were observed: the first referring to the used PDF reader that can interfere with the way it is shown on the screen, such as the disappearance of some cell contours; the second is about the "Specific Construction Details" section where the information in the model of the tax document for NFS-e was not found and therefore it is not being included in the model of danfse.

### CODE REVIEW

**Comment by mileo** [comment]
Can you provide some images?

**Comment by ygcarvalh** [comment]
nfse_pdf_chrome

nfse_pdf_reader

**Comment by ygcarvalh** [comment]
The first image is using Chrome as a reader. The second, just below, is using the Ubuntu document viewer.

This contour problem only happens when you put some background color in the cell.

**Comment by marcelsavegnago** [comment]
> The first image is using Chrome as a reader. The second, just below, is using the Ubuntu document viewer.
> 
> This contour problem only happens when you put some background color in the cell.

Can you send a full print of the document please?

**Comment by ygcarvalh** [comment]
> > The first image is using Chrome as a reader. The second, just below, is using the Ubuntu document viewer.
> > This contour problem only happens when you put some background color in the cell.
> 
> Can you send a full print of the document please?

Don't you prefer that I send the document and you take a test with a different reader?

And just trying to be a little more direct, the error only happens because of the pdf reader and not because of the background colors.

**Comment by ygcarvalh** [comment]
[nfse_without_color.pdf](https://github.com/OCA/l10n-brazil/files/6092006/nfse_without_color.pdf)
[nfse_with_color.pdf](https://github.com/OCA/l10n-brazil/files/6092007/nfse_with_color.pdf)

**Comment by marcelsavegnago** [comment]
@ygcarvalh 
nfse_without_color.pdf ❤️  😄 

For me it continues with the model without colors. It was beautiful: D

**Comment by ygcarvalh** [comment]
I will save the file to be without the colored background. I also thought it was a little cleaner.

**Comment by marcelsavegnago** [comment]
@ygcarvalh terminando dá um toque liberando para revisão fazendo favor.

**Comment by mileo** [comment]
> @ygcarvalh terminando dá um toque liberando para revisão fazendo favor.

Pronto para revisão

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by rvalyi — APPROVED** [review]
LGTM

**Pull request merged**
