### PR TITLE
[8.0] Removed deprecated function amount_to_text replaced by Num2Words

### PR DESCRIPTION
**Pull request by mbcosta**
I tried add Brazilian Portuguese in function amount_to_text https://github.com/odoo/odoo/pull/11388 but the function is deprecated https://github.com/odoo/odoo/pull/12542#issuecomment-237590275 and the best option seems a python library Num2Words https://github.com/savoirfairelinux/num2words. While it not included in Odoo requeriments I put in our localization.

### CODE REVIEW

**Comment by mbcosta** [comment]
To import the lib I use TRY function, the EXCEPT is log message in Odoo the first ideia is use Warning but I got error from Runbot, by this reason I just use INFO log

**Comment by rvalyi** [comment]
:+1:

**Comment by renatonlima** [comment]
:+1:

**Comment by lfdivino** [comment]
:+1:

**Pull request merged**
