### PR TITLE
Migration/l10n br delivery2

### PR DESCRIPTION
**Pull request by mileo**

### CODE REVIEW

**Comment by mileo** [comment]
@renatonlima Já viu esse erro? https://travis-ci.org/OCA/l10n-brazil/jobs/115720111#L1675

**Comment by danimaribeiro** [comment]
The build points to:
"ValueError: Wrong value for product.product.fiscal_type: u'service'"

I would say product_18 from the unit_tests has its type='service',
pick another one.

**Comment by mileo** [comment]
https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_account_product/demo/product_demo.xml#L668



```
    <record id="product.product_product_18" model="product.product">
        <field name="fiscal_type">product</field>
        <field name="fiscal_classification_id" ref="l10n_br_account_product.demo_fiscal_classification_hd"/>
    </record>
```

**Comment by danimaribeiro** [comment]
Really strange, tomorrow I'll take another look at.

**Comment by danimaribeiro** [comment]
I ran the test locally - No problem.
Try to trigger the build again.

**Comment by mileo** [comment]
The option of rebuild can be made only by PSC members... @pedrobaeza Please could you restart travis test?

**Pull request closed without merging**
