### PR TITLE
[8.0] Included Total with Taxes in Invoice Report.

### PR DESCRIPTION
**Pull request by mbcosta**
Today Invoice Repot just have Total without Taxes I included the Total with Taxes

### CODE REVIEW

**Comment by renatonlima** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1:

**Comment by mileo** [comment]
:-1: 

captura de tela de 2016-11-08 19-59-53

captura de tela de 2016-11-08 20-00-18
captura de tela de 2016-11-08 20-00-10
captura de tela de 2016-11-08 20-00-26

**Comment by mileo** [comment]
A falha aconteceu no meu teste:

captura de tela de 2016-11-08 20-18-56

Portanto, conclusão final :+1:

**Pull request merged**
