### PR TITLE
[12.0][BACKPORT][l10n_br_coa_simple] maintainers + dev status + desc

### PR DESCRIPTION
**Pull request by rvalyi**
backport of
https://github.com/OCA/l10n-brazil/commit/ffd1dee2945f6afd89f5a1a4aa1afd34568ce2dd#diff-9f4987d37b654f78b2ffb5ea5fbc7ba2bfe9302391bdad5e51d59787481e87b4

### CODE REVIEW

**Comment by rvalyi** [comment]
CI failed because of #1554
rebuilding...

**Review by marcelsavegnago — APPROVED** [review]

**Review by britoederr — APPROVED** [review]

**Review by renatonlima — APPROVED** [review]

**Comment by rvalyi** [comment]
merge falhando de novo por causa desse #1554 para variar...

**Pull request merged**
