### PR TITLE
Migration/l10n br hr timesheet invoice

### PR DESCRIPTION
**Pull request by mileo**
WIP Tests need!

@biancatella can you work with this tests next week?

### CODE REVIEW

**Comment by rvalyi** [comment]
@mileo is this supposed to superseed https://github.com/OCA/l10n-brazil/pull/246 ?
It seems so. If so please consider remarks in PR 246.

**Comment by danimaribeiro** [comment]
You mean #173

**Comment by rvalyi** [comment]
@danimaribeiro yes PR https://github.com/OCA/l10n-brazil/pull/173 sorry

**Comment by danimaribeiro** [comment]
But this one has some tests, I think we can improve this.

**Comment by mileo** [comment]
@fernandomr Fiz um rebase para remover os conflitos.

**Pull request closed without merging**
