### PR TITLE
[NEW] ODOO-BRAZIL -> OCA: Assegura que a tag NCM tem no maximo 8 digi…

### PR DESCRIPTION
**Pull request by mileo**
…tos 

https://github.com/odoo-brazil/l10n-brazil/pull/48

### CODE REVIEW

**Comment by renatonlima** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1:

**Comment by renatonlima** [comment]
@mileo 

Can you make a rebase?

**Comment by mileo** [comment]
done

**Pull request merged**
