### PR TITLE
14.0 mig l10n br sale commission

### PR DESCRIPTION
**Pull request by DiegoParadeda**

### CODE REVIEW

**Comment by rvalyi** [comment]
@DiegoParadeda seria legal vc dar um squash dos commits [203c820](https://github.com/OCA/l10n-brazil/pull/2680/commits/203c8200e2af0f8cd76ab5029113f762caafac20) e [0c72a9b](https://github.com/OCA/l10n-brazil/pull/2680/commits/0c72a9bb8db0e0a472a1d2482ffe3357cd765bea) e dos commits [ffe46a6](https://github.com/OCA/l10n-brazil/pull/2680/commits/ffe46a67f6014054758733708a358ce497d822b7) e [a02d8b1](https://github.com/OCA/l10n-brazil/pull/2680/commits/a02d8b1f9f636df2c240eccd8a22701b713b701a).

Pode usar `git rebase -i` para isso. Para evitar ter que fazer isso futuramente vc pode usar `git commit --amend` ou `git commit --fixup` quando fizer um commit para resolver algo no commit anterior.

**Review by rvalyi — CHANGES_REQUESTED** [review]
legal que vc fez passar os testes. Vc poderia apenas fazer os squashes que eu mencionei aqui https://github.com/OCA/l10n-brazil/pull/2680#issuecomment-1715840907 por favor?

**Review by mileo — APPROVED** [review]

**Review by rvalyi — APPROVED** [review]
LGTM

**Pull request merged**
