### PR TITLE
[FIX] Altered the string of the field icms_st_mva to explain the type…

### PR DESCRIPTION
**Pull request by sadamo**
… of the MVA (Ajustado)

### CODE REVIEW

**Comment by mileo** [comment]
Please do this on core too: https://github.com/odoo/odoo/blob/9.0/addons/l10n_br/account.py#L23

**Comment by mileo** [comment]
:+1:

**Comment by renatonlima** [comment]
Please, fix this https://travis-ci.org/OCA/l10n-brazil/jobs/97077119

**Comment by renatonlima** [comment]
:+1:

**Pull request merged**
