### PR TITLE
[FIX] Migrate name_get method and remove field name that is not used

### PR DESCRIPTION
**Pull request by danimaribeiro**
name_get working:
fix name_get

### CODE REVIEW

**Comment by mileo** [comment]
LGTM

**Comment by danimaribeiro** [comment]
I'll do for odoo-brazil:
https://github.com/odoo-brazil/l10n-brazil/commit/0d80dfccd49a201d3a83e3cdf0cd65fa6a66c1d6

**Comment by rvalyi** [comment]
:+1:  LGTM sorry for the delay

**Comment by renatonlima** [comment]
:+1:

**Pull request merged**
